# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

elnet_exp <- function(ka, parm, x, y, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, pb, lmu, a0, ca, ia, nin, rsq, alm, nlp, jerr) {
    .Call('_pam_elnet_exp', PACKAGE = 'pam', ka, parm, x, y, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, pb, lmu, a0, ca, ia, nin, rsq, alm, nlp, jerr)
}

spelnet_exp <- function(ka, parm, x, y, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, pb, lmu, a0, ca, ia, nin, rsq, alm, nlp, jerr) {
    .Call('_pam_spelnet_exp', PACKAGE = 'pam', ka, parm, x, y, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, pb, lmu, a0, ca, ia, nin, rsq, alm, nlp, jerr)
}

lognet_exp <- function(parm, x, y, g, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, kopt, pb, lmu, a0, ca, ia, nin, nulldev, dev, alm, nlp, jerr) {
    .Call('_pam_lognet_exp', PACKAGE = 'pam', parm, x, y, g, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, kopt, pb, lmu, a0, ca, ia, nin, nulldev, dev, alm, nlp, jerr)
}

splognet_exp <- function(parm, x, y, g, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, kopt, pb, lmu, a0, ca, ia, nin, nulldev, dev, alm, nlp, jerr) {
    .Call('_pam_splognet_exp', PACKAGE = 'pam', parm, x, y, g, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, kopt, pb, lmu, a0, ca, ia, nin, nulldev, dev, alm, nlp, jerr)
}

fishnet_exp <- function(parm, x, y, g, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, pb, lmu, a0, ca, ia, nin, nulldev, dev, alm, nlp, jerr) {
    .Call('_pam_fishnet_exp', PACKAGE = 'pam', parm, x, y, g, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, pb, lmu, a0, ca, ia, nin, nulldev, dev, alm, nlp, jerr)
}

spfishnet_exp <- function(parm, x, y, g, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, pb, lmu, a0, ca, ia, nin, nulldev, dev, alm, nlp, jerr) {
    .Call('_pam_spfishnet_exp', PACKAGE = 'pam', parm, x, y, g, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, intr, maxit, pb, lmu, a0, ca, ia, nin, nulldev, dev, alm, nlp, jerr)
}

multelnet_exp <- function(parm, x, y, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, jsd, intr, maxit, pb, lmu, a0, ca, ia, nin, rsq, alm, nlp, jerr) {
    .Call('_pam_multelnet_exp', PACKAGE = 'pam', parm, x, y, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, jsd, intr, maxit, pb, lmu, a0, ca, ia, nin, rsq, alm, nlp, jerr)
}

multspelnet_exp <- function(parm, x, y, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, jsd, intr, maxit, pb, lmu, a0, ca, ia, nin, rsq, alm, nlp, jerr) {
    .Call('_pam_multspelnet_exp', PACKAGE = 'pam', parm, x, y, w, jd, vp, mp, cl, ne, nx, nlam, flmin, ulam, thr, isd, jsd, intr, maxit, pb, lmu, a0, ca, ia, nin, rsq, alm, nlp, jerr)
}

get_int_parms <- function(fdev, eps, big, mnlam, devmax, pmin, exmx, itrace) {
    .Call('_pam_get_int_parms', PACKAGE = 'pam', fdev, eps, big, mnlam, devmax, pmin, exmx, itrace)
}

get_int_parms2 <- function(epsnr, mxitnr) {
    .Call('_pam_get_int_parms2', PACKAGE = 'pam', epsnr, mxitnr)
}

chg_fract_dev <- function(arg) {
    invisible(.Call('_pam_chg_fract_dev', PACKAGE = 'pam', arg))
}

chg_dev_max <- function(arg) {
    invisible(.Call('_pam_chg_dev_max', PACKAGE = 'pam', arg))
}

chg_min_flmin <- function(arg) {
    invisible(.Call('_pam_chg_min_flmin', PACKAGE = 'pam', arg))
}

chg_big <- function(arg) {
    invisible(.Call('_pam_chg_big', PACKAGE = 'pam', arg))
}

chg_min_lambdas <- function(irg) {
    invisible(.Call('_pam_chg_min_lambdas', PACKAGE = 'pam', irg))
}

chg_min_null_prob <- function(arg) {
    invisible(.Call('_pam_chg_min_null_prob', PACKAGE = 'pam', arg))
}

chg_max_exp <- function(arg) {
    invisible(.Call('_pam_chg_max_exp', PACKAGE = 'pam', arg))
}

chg_itrace <- function(irg) {
    invisible(.Call('_pam_chg_itrace', PACKAGE = 'pam', irg))
}

chg_bnorm <- function(arg, irg) {
    invisible(.Call('_pam_chg_bnorm', PACKAGE = 'pam', arg, irg))
}

get_bnorm <- function(prec, mxit) {
    .Call('_pam_get_bnorm', PACKAGE = 'pam', prec, mxit)
}

chg_epsnr <- function(arg) {
    invisible(.Call('_pam_chg_epsnr', PACKAGE = 'pam', arg))
}

chg_mxitnr <- function(irg) {
    invisible(.Call('_pam_chg_mxitnr', PACKAGE = 'pam', irg))
}

wls_exp <- function(alm0, almc, alpha, m, no, ni, x, r, xv, v, intr, ju, vp, mp, cl, nx, thr, maxit, a, aint, g, ia, iy, iz, mm, nino, rsqc, nlp, jerr) {
    .Call('_pam_wls_exp', PACKAGE = 'pam', alm0, almc, alpha, m, no, ni, x, r, xv, v, intr, ju, vp, mp, cl, nx, thr, maxit, a, aint, g, ia, iy, iz, mm, nino, rsqc, nlp, jerr)
}

spwls_exp <- function(alm0, almc, alpha, m, no, ni, x, xm, xs, r, xv, v, intr, ju, vp, mp, cl, nx, thr, maxit, a, aint, g, ia, iy, iz, mm, nino, rsqc, nlp, jerr) {
    .Call('_pam_spwls_exp', PACKAGE = 'pam', alm0, almc, alpha, m, no, ni, x, xm, xs, r, xv, v, intr, ju, vp, mp, cl, nx, thr, maxit, a, aint, g, ia, iy, iz, mm, nino, rsqc, nlp, jerr)
}

